// Copyright 2018 Ionx Solutions (https://www.ionxsolutions.com)
// Ionx Solutions licenses this file to you under the Apache License, 
// Version 2.0. You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0

namespace Serilog.Sinks.Syslog
{
    /// <summary>
    /// The category of the system or application that generated a syslog message
    /// </summary>
    public enum Facility
    {
        /// <summary>
        /// Kernel messages
        /// </summary>
        Kernel = 0,

        /// <summary>
        /// User-level messages
        /// </summary>
        User = 1,

        /// <summary>
        /// Mail system
        /// </summary>
        Mail = 2,

        /// <summary>
        /// System daemons
        /// </summary>
        Daemons = 3,

        /// <summary>
        /// Security/authorisation messages
        /// </summary>
        Auth = 4,

        /// <summary>
        /// Messages generated by the syslog daemon itself
        /// </summary>
        Syslog = 5,

        /// <summary>
        /// Line printer subsystem
        /// </summary>
        LPR = 6,

        /// <summary>
        /// Network news subsystem
        /// </summary>
        News = 7,

        /// <summary>
        /// UUCP subsystem
        /// </summary>
        UUCP = 8,

        /// <summary>
        /// Cron scheduler daemon
        /// </summary>
        Cron = 9,

        /// <summary>
        /// Security/authorisation messages (private)
        /// </summary>
        Auth2 = 10,

        /// <summary>
        /// FTP daemon
        /// </summary>
        FTP = 11,

        /// <summary>
        /// NTP subsystem
        /// </summary>
        NTP = 12,

        /// <summary>
        /// Log audit
        /// </summary>
        LogAudit = 13,

        /// <summary>
        /// Log alert
        /// </summary>
        LogAlert = 14,

        /// <summary>
        /// Cron scheduler daemon
        /// </summary>
        Cron2 = 15,

        /// <summary>
        /// Reserved for local use (0)
        /// </summary>
        Local0 = 16,

        /// <summary>
        /// Reserved for local use (0)
        /// </summary>
        Local1 = 17,

        /// <summary>
        /// Reserved for local use (0)
        /// </summary>
        Local2 = 18,

        /// <summary>
        /// Reserved for local use (0)
        /// </summary>
        Local3 = 19,

        /// <summary>
        /// Reserved for local use (0)
        /// </summary>
        Local4 = 20,

        /// <summary>
        /// Reserved for local use (0)
        /// </summary>
        Local5 = 21,

        /// <summary>
        /// Reserved for local use (0)
        /// </summary>
        Local6 = 22,

        /// <summary>
        /// Reserved for local use (0)
        /// </summary>
        Local7 = 23
    }
}
